import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TicketQueueProvider } from '@/context/TicketQueueContext/TicketQueueContext'
import { ZoneProvider } from '@/context/ZoneContext/ZoneContext'
import { TeamProvider } from '@/context/TeamContext/TeamContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>ZATS</title>
      </head>
      <body>
        <TeamProvider>
           <ZoneProvider>
            <TicketQueueProvider>
              {children}
            </TicketQueueProvider>
          </ZoneProvider>
        </TeamProvider>
      </body>
    </html>
  )
}
